# -*- coding: utf-8 -*-
"""Gráfico Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1taCyAPeKNhEefk63qoTbiVCDeWLOjdLF
"""

!pip install --upgrade pip setuptools wheel

!pip install seaborn --prefer-binary

!pip freeze > requirements.txt

"""Gráfico 01"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

sns.set_style('whitegrid') # outros estilo como (darkrid, whitegrid, dark, white, ticks)

ados = { 'Amostra A': [1, 4, 2, 3],
          'Amostra B': [2, 8, 4, 6],
          'Amostra C': [4, 16, 8, 12]
         }
indices = [1, 2, 3, 4]

df = pd.DataFrame(data=dados, index=indices)

plot = sns.lineplot(df)

plot.set_title('Titulo do Gráfico')
plot.set_xlabel('Label X')
plot.set_ylabel('Label Y')


plt.show()

"""Gráfico de barra com Seaborn"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

dados = {'Frutas': ['Laranja', 'Melancia', 'Manga', 'Jaca'],
         'Quantidades': [60, 100, 85, 30]
        }
df = pd.DataFrame(data=dados)

sns.barplot(df, x='Frutas', y='Quantidades')

plt.show()

"""Histrograma com Seaborn"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pesquisa = np.random.normal(170, 10, 250)

df = pd.DataFrame(data=pesquisa)

sns.histplot(df, bins=8, linewidth=0.5, edgecolor='#ffffff', legend=False)

plt.show()

"""Gráfico de Pizza com Seaborn"""

import seaborn as sns
import matplotlib.pyplot as plt

labels = ['Uva', 'Morango', 'Abacaxi', 'Mamão']
porcentagens = [15, 30, 45, 10]

cores = sns.color_palette('pastel')[0:5]

plt.pie(porcentagens, colors=cores, labels=labels, autopct = '%1.2f%%')

plt.show()

cores

"""Salvando imagem do Gráfico"""

import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

labels = ['Uva', 'Morango', 'Abacaxi', 'Mamão']
porcentagens = [15, 30, 45, 10]

cores = sns.color_palette('pastel')[0:5]

plt.pie(porcentagens, colors=cores, labels=labels, autopct = '%1.2f%%')

plt.savefig('meu_grafico.png')

plt.show()

# segundo exemplo

import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

labels = ['Uva', 'Morango', 'Abacaxi', 'Mamão']
porcentagens = [15, 30, 45, 10]

cores = sns.color_palette('pastel')[0:5]

plt.pie(porcentagens, colors=cores, labels=labels, autopct = '%1.2f%%')

plt.savefig('meu_grafico2.png', transparent = True, dpi = 150, bbox_inches = 'tight')

plt.show()